import placeholder from "@/components/ui/image.png"

export const profilesData = [
    {
      id: "1",
      name: "Emma Johnson",
      age: 8,
      profileImage: placeholder,
      hasActiveSubscription: true,
      subscriptionType: "Premium Monthly",
      totalBadges: 12,
      totalPoints: 850,
      currentStreak: 15,
      badges: [
        {
          id: "1",
          name: "First Stroke",
          description: "Completed your first swimming stroke",
          category: "Milestone",
          icon: "🏊‍♀️",
          color: "bg-blue-500",
          earnedDate: "2024-01-15",
          rarity: "Common",
          points: 50,
        },
        {
          id: "2",
          name: "Freestyle Master",
          description: "Mastered the freestyle swimming technique",
          category: "Skill",
          icon: "🏆",
          color: "bg-yellow-500",
          earnedDate: "2024-02-20",
          rarity: "Rare",
          points: 100,
        },
        {
          id: "3",
          name: "Perfect Attendance",
          description: "Attended all classes for a full month",
          category: "Attendance",
          icon: "⭐",
          color: "bg-green-500",
          earnedDate: "2024-03-01",
          rarity: "Epic",
          points: 150,
        },
        {
          id: "4",
          name: "Backstroke Beginner",
          description: "Successfully learned backstroke basics",
          category: "Skill",
          icon: "🌊",
          color: "bg-cyan-500",
          earnedDate: "2024-02-10",
          rarity: "Common",
          points: 75,
        },
        {
          id: "5",
          name: "Safety First",
          description: "Demonstrated excellent water safety knowledge",
          category: "Safety",
          icon: "🛡️",
          color: "bg-red-500",
          earnedDate: "2024-01-25",
          rarity: "Uncommon",
          points: 80,
        },
        {
          id: "6",
          name: "Team Player",
          description: "Showed great teamwork during group activities",
          category: "Social",
          icon: "🤝",
          color: "bg-purple-500",
          earnedDate: "2024-02-15",
          rarity: "Uncommon",
          points: 60,
        },
        {
          id: "7",
          name: "Distance Swimmer",
          description: "Swam 25 meters without stopping",
          category: "Milestone",
          icon: "🎯",
          color: "bg-orange-500",
          earnedDate: "2024-03-10",
          rarity: "Rare",
          points: 120,
        },
        {
          id: "8",
          name: "Quick Learner",
          description: "Mastered a new technique in record time",
          category: "Achievement",
          icon: "⚡",
          color: "bg-indigo-500",
          earnedDate: "2024-02-28",
          rarity: "Epic",
          points: 140,
        },
      ],
      upcomingBadges: [
        {
          name: "Butterfly Beginner",
          description: "Learn the butterfly stroke basics",
          progress: 60,
          category: "Skill",
          icon: "🦋",
          estimatedDate: "2024-04-15",
        },
        {
          name: "50m Champion",
          description: "Swim 50 meters continuously",
          progress: 35,
          category: "Milestone",
          icon: "🏅",
          estimatedDate: "2024-05-01",
        },
        {
          name: "Diving Expert",
          description: "Master diving techniques",
          progress: 20,
          category: "Skill",
          icon: "🤿",
          estimatedDate: "2024-06-01",
        },
      ],
    },
    {
      id: "2",
      name: "Lucas Johnson",
      age: 6,
      profileImage: placeholder,
      hasActiveSubscription: false,
      subscriptionType: null,
      totalBadges: 3,
      totalPoints: 180,
      currentStreak: 5,
      badges: [
        {
          id: "1",
          name: "Water Confidence",
          description: "Became comfortable in the water",
          category: "Milestone",
          icon: "💧",
          color: "bg-blue-400",
          earnedDate: "2024-02-10",
          rarity: "Common",
          points: 50,
        },
        {
          id: "2",
          name: "First Float",
          description: "Successfully floated for 10 seconds",
          category: "Skill",
          icon: "🌊",
          color: "bg-cyan-400",
          earnedDate: "2024-03-05",
          rarity: "Common",
          points: 60,
        },
        {
          id: "3",
          name: "Brave Swimmer",
          description: "Overcame fear of deep water",
          category: "Achievement",
          icon: "🦁",
          color: "bg-yellow-400",
          earnedDate: "2024-03-15",
          rarity: "Uncommon",
          points: 70,
        },
      ],
      upcomingBadges: [
        {
          name: "Kick Master",
          description: "Perfect your kicking technique",
          progress: 45,
          category: "Skill",
          icon: "🦵",
          estimatedDate: "2024-04-20",
        },
      ],
    },
  ]
